# Global configuration
sonar.host.url=https://sonarcloud.io
sonar.organization=prateek-02
sonar.projectKey=Prateek-02_Job-Portal-Management-System
sonar.projectName=Job Portal Management System
sonar.projectVersion=1.0

# Encoding of the source code
sonar.sourceEncoding=UTF-8

# List of modules
sonar.modules=frontend,auth-service,job-service,application-service,api-gateway

# --- Frontend Module ---
frontend.sonar.projectBaseDir=job-portal-frontend
frontend.sonar.sources=src
frontend.sonar.tests=src
frontend.sonar.test.inclusions=**/*.spec.ts
frontend.sonar.exclusions=**/node_modules/**,**/dist/**,**/public/**
frontend.sonar.javascript.lcov.reportPaths=coverage/job-portal-frontend/lcov.info

# --- Backend Modules (Java) ---
sonar.java.binaries=**/target/classes
sonar.java.test.binaries=**/target/test-classes
sonar.coverage.jacoco.xmlReportPaths=**/target/site/jacoco/jacoco.xml

auth-service.sonar.projectBaseDir=Job-Portal-Backend/AuthService
auth-service.sonar.sources=src/main/java
auth-service.sonar.tests=src/test/java

job-service.sonar.projectBaseDir=Job-Portal-Backend/JobService
job-service.sonar.sources=src/main/java
job-service.sonar.tests=src/test/java

application-service.sonar.projectBaseDir=Job-Portal-Backend/ApplicationService
application-service.sonar.sources=src/main/java
application-service.sonar.tests=src/test/java

api-gateway.sonar.projectBaseDir=Job-Portal-Backend/ApiGateway
api-gateway.sonar.sources=src/main/java
api-gateway.sonar.tests=src/test/java
