server.port=8761

spring.application.name=eureka-server

eureka.instance.hostname=eureka-server
eureka.instance.prefer-ip-address=true

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/

# Actuator
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health,info,metrics,env,beans

# Zipkin
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans

# Logging pattern (ADD THIS)
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]