# =====================================================
# Server Configuration
# =====================================================
server.port=8086
spring.application.name=notification-service

# =====================================================
# Eureka Configuration
# =====================================================
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true

# =====================================================
# Internal Configuration
# =====================================================
internal.secret=${INTERNAL_SECRET}

# =====================================================
# RabbitMQ Configuration
# =====================================================
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

# =====================================================
# Gmail SMTP Configuration
# =====================================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# =====================================================
# Queue Names
# =====================================================
rabbitmq.queue.job.posted=email.job-posted
rabbitmq.queue.job.applied=email.job-applied
rabbitmq.queue.application.status=email.application-status

# Circuit Breaker (Resilience4j)
resilience4j.circuitbreaker.instances.notificationAuthService.register-health-indicator=true
resilience4j.circuitbreaker.instances.notificationAuthService.sliding-window-size=10
resilience4j.circuitbreaker.instances.notificationAuthService.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.notificationAuthService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.notificationAuthService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.notificationAuthService.permitted-number-of-calls-in-half-open-state=3

# Time Limiter (Resilience4j)
resilience4j.timelimiter.instances.notificationAuthService.timeout-duration=15s

# =====================================================
# Actuator
# =====================================================
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health,info,metrics,env,beans,circuitbreakers

# Zipkin
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans

# Logging pattern (ADD THIS)
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
