# =====================================================
# Server Configuration
# =====================================================
server.port=8081

# =====================================================
# Application Name
# =====================================================
spring.application.name=auth-service

# =====================================================
# MySQL Database Configuration
# =====================================================
spring.datasource.url=jdbc:mysql://mysql:3306/job_portal_db
spring.datasource.username=root
spring.datasource.password=${MYSQL_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =====================================================
# JPA / Hibernate Configuration
# =====================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# =====================================================
# JWT Configuration
# =====================================================
jwt.secret=${JWT_SECRET}
jwt.expiration=900000
jwt.refresh.expiration=604800000


# =====================================================
# Internal Configuration
# =====================================================
internal.secret=${INTERNAL_SECRET}

# Cloudinary
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# RabbitMQ
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

#Admin Details
admin.email=${ADMIN_EMAIL}
admin.password=${ADMIN_PASSWORD}
admin.name=${ADMIN_NAME}
admin.phone=${ADMIN_PHONE}


# =====================================================
# Eureka Client Configuration
# =====================================================
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true

# =====================================================
# Actuator
# =====================================================
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health,info,metrics,env,beans,circuitbreakers,prometheus

# Zipkin
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans

# Logging pattern (ADD THIS)
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]

# =====================================================
# Mail SMTP Configuration
# =====================================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# =====================================================
# Frontend Configuration
# =====================================================
app.frontend-url=${FRONTEND_URL}

